lib/phx_react_web/router.ex
defmodule PhxReactWeb.Router do
  use PhxReactWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PhxReactWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhxReactWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", PhxReactWeb do
    pipe_through :api

    get "/health", HealthController, :index
  end

  scope "/app", PhxReactWeb do
    get "/", WebappController, :index
    get "/*path", WebappController, :index
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PhxReactWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/mix/tasks/webapp.ex
defmodule Mix.Tasks.Webapp do
  @moduledoc """
    React frontend compilation and bundling for production.
  """
  use Mix.Task
  require Logger
  # Path for the frontend static assets that are being served
  # from our Phoenix router when accessing /app/* for the first time
  @public_path "./priv/static/webapp"

  @shortdoc "Compile and bundle React frontend for production"
  def run(_) do
    Logger.info("📦 - Installing NPM packages")
    System.cmd("npm", ["install", "--quiet"], cd: "./frontend")

    Logger.info("⚙️  - Compiling React frontend")
    System.cmd("npm", ["run", "build"], cd: "./frontend")

    Logger.info("🚛 - Moving dist folder to Phoenix at #{@public_path}")

    # First clean up any stale files from previous builds if any
    with {_, 0} <- System.shell("build-frontend.sh") do
      Logger.info("⚛️  - React frontend ready.")
    else
      {_, status} -> Logger.error("Error. Exit status: #{status}")
    end
  end
end

lib/phx_react/application.ex
defmodule PhxReact.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      PhxReact.Repo,
      # Start the Telemetry supervisor
      PhxReactWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: PhxReact.PubSub},
      # Start the Endpoint (http/https)
      PhxReactWeb.Endpoint
      # Start a worker by calling: PhxReact.Worker.start_link(arg)
      # {PhxReact.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: PhxReact.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    PhxReactWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/phx_react/mailer.ex
defmodule PhxReact.Mailer do
  use Swoosh.Mailer, otp_app: :phx_react
end

lib/phx_react/repo.ex
defmodule PhxReact.Repo do
  use Ecto.Repo,
    otp_app: :phx_react,
    adapter: Ecto.Adapters.Postgres
end

lib/phx_react_web/controllers/health_controller.ex
defmodule PhxReactWeb.HealthController do
  # pulls in plug macros
  use PhxReactWeb, :controller

  def index(conn, _params) do
    send_resp(conn, 204, "")
  end
end

lib/phx_react_web/controllers/page_controller.ex
defmodule PhxReactWeb.PageController do
  use PhxReactWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/phx_react_web/controllers/webapp_controller.ex
defmodule PhxReactWeb.WebappController do
  use PhxReactWeb, :controller

  def index(conn, _params) do
    conn
    |> send_resp(200, render_vue_app())
  end

  # Serve the index.html file as-is and let React
  # take care of the rendering and client-side rounting.
  #
  # Potential improvement: Cache the file contents here
  # in an ETS table so we don't read from the disk for every request.
  defp render_vue_app() do
    Application.app_dir(:phx_react, "/priv/static/webapp/dist/index.html")
    |> File.read!()
  end
end

lib/phx_react_web/views/error_view.ex
defmodule PhxReactWeb.ErrorView do
  use PhxReactWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/phx_react_web/views/layout_view.ex
defmodule PhxReactWeb.LayoutView do
  use PhxReactWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/phx_react_web/views/page_view.ex
defmodule PhxReactWeb.PageView do
  use PhxReactWeb, :view
end

lib/phx_react_web/templates/layout/app.html.heex
<main class="flex justify-center">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/phx_react_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/phx_react_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "PhxStack", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header class="px-6 py-4 text-right">
      <nav class="uppercase font-mono font-semibold">
        <ul class="space-x-4">
          <%!-- <li class="inline-block"><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li> --%>
          <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
            <li class="inline-block hover:text-red-600"><%= link "Dashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
          <% end %>
        </ul>
      </nav>
      <div class="flex justify-center">
        <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo" />
      </div>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/phx_react_web/templates/page/index.html.heex
<section class="text-center space-y-4">
  <h1 class="text-6xl font-black">
    <%= gettext "Welcome, %{name}", name: "Aron" %>
  </h1>
  <p class="dark:text-white font-mono text-xl">Peace of mind from prototype to production</p>
  <button role="navigation" class="btn rounded shadow-sm border-2 border-yellow-400/20 px-3 py-1 text-base font-medium bg-yellow-400 hover:bg-yellow-300">
    <%= link "App", to: Routes.webapp_path(@conn, :index) %>
  </button>
</section>